
DROP TABLE IF EXISTS Invoice;
DROP TABLE IF EXISTS Payment;
DROP TABLE IF EXISTS AuditRecord;
DROP TABLE IF EXISTS Revenue;
DROP TABLE IF EXISTS Expense;
DROP TABLE IF EXISTS ExpenseTypes;
DROP TABLE IF EXISTS FinancialAudit;
DROP TABLE IF EXISTS TaxReport;
